spring.application.name=ecom-application
# Petstore URL ko default hone se rokein
"""springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.disable-swagger-default-url=true""""